model:
  output_size: 2
  layers: [256, 128, 64, 32]
training:
  epochs: 150
  batch_size: 16
  learning_rate: 0.0001
data:
  train_path: data/train_data_RTMpose_zeroized_conf.csv
  validation_path: data/coco_validation_data.csv
device: cpu
